### ISSUE TITLE
you can't drag the drawbars in Organ 3

### ISSUE THREAD

**Issue by squinkylabs** [kockie69/SquinkyVCV-main#7]
![image](https://user-images.githubusercontent.com/16314838/135545708-2c41f755-472d-40e7-a169-1a0b31f672eb.png)

**Comment by pgatt** [comment]
Nor can you right click the module without it crashing here.

**Comment by kockie69** [comment]
What platform is this on? As on Windows I can't reproduce....

**Comment by pgatt** [comment]
> What platform is this on? As on Windows I can't reproduce....

Sorry that's probably the worst bug report ever. Mac build. It may have been user error or something else going on - I've built and updat d plugins that weren't building - and given that I have little recent programming experience I may have mucked things up.

**Comment by kockie69** [comment]
Oh I see. So maybe would be better you report the errors you get with the build as these might be caused by your own fixes. You can see if you can get the latest repo and rebuild to see if the errors are gone. Or otherwise raise it as a seperate issue please. I want to keep this one seperate for the non sliding issue.

**Comment by kockie69** [comment]
I commented out some code here, so that looked like the reason why it wasn't working. But after funcommenting and fixing the code it is still not working. Looks a bit like an issue with Rack. I will keep this one open until I get a chance to build against the latest SDK to see if it is still a problem

**Comment by squinkylabs** [comment]
on windows right click does not crash for me. And now that the redundant manual link is gone that module doesn't seem to do any menu processing at all, so the crash was probably from elsewhere.

**Comment by kockie69** [comment]
The sliders are working again.

**Comment by squinkylabs** [comment]
They do drag now. They are more "finicky" than they used to be. For example, you can now drag in the area to the left of the numeric scale and it will drag the "thumb". But if you try to drag in the are to the right of the numeric scale it doesn't drag. The "active area" seems quite a bit smaller than it used to be. Which is ok, of course, but it means that maybe half the time I try to drag a slider I miss and it doesn't drag.
